Analyse des signaux médicaux - Séance 1 de TP
--

At the end of this session, you will be able to :
- Create and manage the Jupyter Notebooks environment to run code, insert text and math equations
- Perform basic matrix manipulations using Numpy
- Create signals and perform basic scientific computing using Scipy and Numpy
- Produce simple data visulisation using Matplotlib
- Open, manipulate and visualize an EEG dataset used in the course

In [1]:
!pip install mne

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 33.5 MB/s eta 0:00:00


Part 1 - Intro to Jupyter Notebook
--
Here, we will only cover the basics. You can skip this part if you are already familiar with jupyter notebook.

Jupyter Notebook is based on the .ipynb format (iPython Notebook), and is essentially a way to do rapid prototyping / demon of code / visualisation of scientific python. The basic idea is to define *cells*.
Cells can be of several types, including python code, or rich text (using [markdown formatting](https://www.markdownguide.org/basic-syntax/)).

When a code cell is evaluated (i.e. the python code will be executed), the output of this evaluation will show up right below the cell.

When a text cell is evaluated, the text will be formatted.

Please now do the "User Interface Tour" from the Help menu.

Done ?

When working with Jupyter Notebook, you will essentially switch between two modes :
- The Edit mode in which you edit the content of the cells
- The Command mode, that enables you to change the cell types.

When in Command mode, you can select cells. If you select a single cell, you can edit it by simply pressing enter, or double clicking on it.

For example, try editing THIS CELL and change its content.

Now, edit the cell below, change the code, and when you're done, press Shift+Enter to evalute the code.

In [3]:
### CELL TO BE EDITED

a=32
b= 2*a
c=a+b
print(c,"=","%d + %d"%(a,b))

96 = 32 + 64


Text cells can contain math expressions that use the Markdown formatting, in which you can use LaTEx expressions for maths (enclosed between two dollar signs).

For example : $A(k) \triangleq \sum_{\mathbf{n} =1}^{k}{n^2}$

Now :
- Edit the current cell to show the code that displays the math expression,
- Create a code cell below that defines a function that calculates $A(k)$ given k, and evaluate this cell,
- Create another cell and use the function to display $A(k)$ for a few values of $\mathbf{k}$ (eg 10 and 20).

In [4]:
### CELL TO BE COMPLETED

def A(k):
    result = 0
    for n in range(k+1):
      result = result + n**2

    return result


In [9]:
### CELL TO BE COMPLETED
print( "A(10)=",A(10), "A(20)=",A(20))

A(10)= 385 A(20)= 2870


Note that using Jupyter Notebook, if you evaluate a cell with a function followed by a "?" sign, the help of the function will pop up.

Example :

In [10]:
import os

os.listdir?

You can also display the code of a function using the syntax "??"

In [11]:
A??

The popup can be closed by pressing the Escape key.

Use the listdir function to browse the content of some directories...


In [12]:
os.listdir('../')

['usr',
 'home',
 'lib64',
 'var',
 'root',
 'sbin',
 'srv',
 'proc',
 'mnt',
 'dev',
 'lib',
 'bin',
 'media',
 'opt',
 'boot',
 'etc',
 'run',
 'lib32',
 'libx32',
 'tmp',
 'sys',
 'kaggle',
 '.dockerenv',
 'datalab',
 'tools',
 'content',
 'python-apt',
 'python-apt.tar.xz']

In [13]:
os.listdir('./')

['.config', 'sample_data']

Part 2 - Introduction to Numpy, Scipy and Matplotlib
--

A code cell can contain any python code, including imports. Let's start by importing the Numpy package.

In [14]:
import numpy as np

Numpy can be used to generate pseudo-random values from various distributions. In particular, a very useful distribution is the standard normal (zero mean and unit variance). Let's generate two vectors sampled from the normal distribution, using a length parameter that we'll be able to change if needed.

In [21]:
length = 50

vecA = np.random.randn(length)
vecB = np.random.randn(2*length)

vecA and vecB are numpy *arrays*. One of their attributes can be fetched to check their *shape*

In [22]:
print(vecA.shape)
print(vecB.shape)

(50,)
(100,)


In [23]:
print(vecA)

[ 0.24297878 -0.1829261  -1.35527544 -1.13857885  0.01087697  0.66341624
  0.91698721  0.60150652  1.61465382 -0.29659171 -0.46663449  1.45890035
  1.58947293  0.2790603   0.8779805  -1.07934419 -0.64494796  0.1085374
 -0.77334867 -0.20259783 -1.14137164  0.09227134 -0.78001631  0.01000362
 -1.95477022  0.13834059  0.62098238  0.19562209 -0.48579233 -0.18285405
 -1.95370698 -0.72083512  1.52665387  0.18592274 -0.8426288   1.39288951
  1.26736169 -0.3140338   1.03499259  0.11309575 -1.57807126 -1.25353609
 -1.72409161 -0.59873565 -0.80143524 -0.45525799  1.18991665 -0.20621368
 -1.7887386   0.72532809]


Numpy arrays can be vectors as well as matrices, or any tensor. For example the following code will create a 3 x length matrix, using the standard normal

In [24]:
matC = np.random.randn(3,length)

In [25]:
matC.shape

(3, 50)

In [27]:
matC

array([[ 1.30810314, -0.47564045, -1.05033872,  0.50148904,  0.50659749,
        -0.13065178,  0.5277054 ,  0.01535292,  1.56578493, -0.8673546 ,
         2.35189087,  0.19646664,  1.10803984, -0.31158547,  1.22490438,
        -2.26554269,  0.51596398, -0.72454831, -1.25157865,  0.10371042,
        -1.76498547, -0.67784425,  1.03673708,  0.19182255,  0.68478404,
         1.24169325, -0.0064476 , -1.876102  ,  0.67739258, -1.41232584,
        -0.01713274, -0.12415775,  0.81050278,  0.17854138, -0.04959261,
        -0.7592192 ,  1.70350954, -0.31002665,  0.03639764, -0.31903255,
        -0.89930111, -0.61746893,  1.80702059,  0.09573157,  1.03869187,
        -2.36580925, -0.21201422, -0.2999618 , -0.74176573, -0.84611847],
       [ 0.29456928,  0.38445882,  0.04134304,  0.50658742,  0.60312635,
        -0.25076983, -0.39615491,  0.87062459,  0.85449214,  2.06165388,
         0.11476532, -0.99816904, -1.06221724, -0.83501641,  0.71011878,
         0.37264667,  1.2280064 , -1.50503226, -1.

This could be used for instance for EEG signals in the time frequency domain. Let's imagine we have Power Spectral Density in 10 frequency bands, 1 second at 500 Hz, and 5 electrodes. We can generate a random signal with such shape by using numpy random generators.

Check the syntax of the np.random.randn function, and generate an array called EEG_timefreq, with the specifications  (10 frequency bands, 1 second at 500 Hz, and 5 electrodes)

In [36]:
EEG_timefreq = np.random.randn(10,500,5)


Note that the random package of Numpy has several other interesting functions. Try to test the two functions proposed in the cell below.

Try uncommenting the two functions below one by one, look up their help page, and try to use them.

In [38]:
### CELL TO BE COMPLETED  (2-2)

Y= np.random.randint(0,2,size =(2,3))

X = np.random.permutation(EEG_timefreq)
print(X,Y)

[[[-1.67811723  1.1113989  -0.18403795 -0.16513288 -0.2430885 ]
  [-0.54136052  0.57680497 -2.40438932  0.9192231  -1.00399314]
  [ 0.23817318 -1.15696564 -0.11002418 -1.02443592  0.21531657]
  ...
  [-0.94843079  0.71622232 -0.45412381  0.64057613  0.6037435 ]
  [ 0.11652044 -0.51608734  1.64712306 -1.5506746  -1.06127313]
  [ 1.71068575  1.37828095  2.8929843  -2.12302252  0.3066599 ]]

 [[-0.80006405 -1.0075519   0.27793602  1.62805908  0.301262  ]
  [ 0.32179578  0.5073821   1.24379423  1.17523489 -0.41538221]
  [-0.69482511 -0.0884721   0.93825495  0.93988357  0.9845921 ]
  ...
  [ 0.26589448 -1.19994024  0.0125446   0.75425396  1.08696515]
  [-0.07613234 -0.07916267 -0.69847092  0.1540724   0.46785791]
  [ 1.28360766 -0.42384336 -1.17161391 -0.47614708 -1.09735151]]

 [[-2.55711909  1.40033071 -0.66857477  0.045402   -0.29845458]
  [-0.69930434  2.1316214   1.11820804 -1.5710909  -0.13152647]
  [ 0.91261029  0.67036643 -0.70992715  0.72008252 -0.24210058]
  ...
  [-0.31926518 -0.

A very important features of arrays is the fact they can be used as *iterables*. For example, you can iterate over the dimensions of an array by simply "looping" over it using a *for* loop

In [41]:
for freqband in EEG_timefreq:
  print(freqband)
  print(freqband.shape)

[[-1.67811723  1.1113989  -0.18403795 -0.16513288 -0.2430885 ]
 [-0.54136052  0.57680497 -2.40438932  0.9192231  -1.00399314]
 [ 0.23817318 -1.15696564 -0.11002418 -1.02443592  0.21531657]
 ...
 [-0.94843079  0.71622232 -0.45412381  0.64057613  0.6037435 ]
 [ 0.11652044 -0.51608734  1.64712306 -1.5506746  -1.06127313]
 [ 1.71068575  1.37828095  2.8929843  -2.12302252  0.3066599 ]]
(500, 5)
[[-1.19842451  0.33080605  1.24212416  0.21889588 -0.80862291]
 [-0.93910865 -0.89089875 -0.07138805  0.59560354 -1.17082687]
 [-1.26410142 -0.51799329 -1.21033451 -1.20255857 -1.55882285]
 ...
 [ 0.65081161 -0.38681993 -0.33689197  1.40115656 -1.24109731]
 [-0.79110962  1.66879045 -0.42864975  0.56183654  1.20036792]
 [ 0.50346044 -1.32968662 -0.14205401  1.31281316 -0.81063674]]
(500, 5)
[[ 0.66487599  1.31049116  1.55149629 -1.12019714 -1.02781269]
 [-0.56756804 -0.11672938  0.11055249  0.97587345  0.06887962]
 [-1.58013413  0.0893273  -0.65404023  0.56522181  1.09854112]
 ...
 [-0.3785664  -1.231

This way, we can loop over frequency bands, and process each frequency band separately.

Also possible to enumerate along the dimension in order to get the index of the current "smaller" array


In [42]:
print('Initial shape is %d %d %d' % (EEG_timefreq.shape[0],EEG_timefreq.shape[1],EEG_timefreq.shape[2]))
print('Iterating over the first dimension using an index k')
for k,curdim in enumerate(EEG_timefreq):
    print('k = %d, shape is %d %d' % (k,curdim.shape[0],curdim.shape[1]))

Initial shape is 10 500 5
Iterating over the first dimension using an index k
k = 0, shape is 500 5
k = 1, shape is 500 5
k = 2, shape is 500 5
k = 3, shape is 500 5
k = 4, shape is 500 5
k = 5, shape is 500 5
k = 6, shape is 500 5
k = 7, shape is 500 5
k = 8, shape is 500 5
k = 9, shape is 500 5


Now let's imagine we want to calculate the average power over time and electrode, for each couple frequency band.

Use the previous principle in order to calculate the average of each frequency band subvector, using the function np.mean()

In [46]:

np.mean(EEG_timefreq, axis = 0)

array([[-0.71358881,  0.23258421,  0.27417772, -0.16438326, -0.48191343],
       [-0.37975651,  0.05174667, -0.13703267,  0.1157627 , -0.33751836],
       [-0.14339268, -0.28989141, -0.01774009, -0.02182751,  0.4663713 ],
       ...,
       [ 0.17173241, -0.3651702 , -0.24504674,  0.42170006, -0.04854635],
       [ 0.16794314, -0.26723123, -0.09756685,  0.5155082 ,  0.17186799],
       [ 0.38255768, -0.1341711 ,  0.42296168, -0.09384027, -0.37429534]])

Check that you obtain the same result when directly computing the average over the two axis 1 and 2 (look up the arguments of np.mean), which correspond to averaging in time and electrode.

In [52]:
#np.mean(EEG_timefreq, axis = 1)
#np.mean(EEG_timefreq, axis = 2)
np.mean(EEG_timefreq, axis = (1,2))

array([ 0.0288283 ,  0.02548798, -0.00313524,  0.00955294, -0.01357968,
        0.00331787,  0.02152748, -0.00243077,  0.02869282, -0.00111552])

These features will prove to be very useful when manipulate large arrays.

Another important operation when working with Numpy Arrays is *reshaping*. Essentially, *reshaping* consists in changing the organisation of the array (in terms of dimension), while keeping the same number of elements. For example, a 20x10 2D array can be converted into a 4x5x10 array

In [53]:
A = np.random.randint(1,5,(10,20))
print('Initial shape of A is %d x %d' % (A.shape[0],A.shape[1]))
print(A)
B = A.reshape((4,5,10))
print('B is A reshaped to %d x %d x %d' % (B.shape[0],B.shape[1],B.shape[2]))
print(B)

Initial shape of A is 10 x 20
[[2 1 2 3 1 4 3 4 4 2 3 4 2 3 1 4 3 2 4 1]
 [2 2 2 4 2 4 2 3 3 4 1 2 3 1 1 4 4 1 2 2]
 [2 4 2 1 4 4 4 3 1 2 2 4 4 4 1 1 4 3 3 1]
 [1 2 4 3 2 1 1 4 2 2 3 2 2 4 2 4 3 3 4 3]
 [3 2 4 1 1 3 3 3 3 4 4 3 4 4 2 4 2 4 1 2]
 [3 3 1 4 1 2 2 4 3 3 4 1 2 2 1 2 2 4 4 1]
 [3 4 3 1 2 3 4 4 4 1 1 2 3 4 3 4 2 1 4 3]
 [2 4 1 2 3 4 4 4 2 2 4 3 3 3 1 3 4 1 4 2]
 [4 4 4 1 2 4 4 1 1 3 4 3 4 1 3 2 1 3 1 1]
 [3 4 2 4 3 2 3 3 1 4 1 2 3 1 4 1 4 2 4 4]]
B is A reshaped to 4 x 5 x 10
[[[2 1 2 3 1 4 3 4 4 2]
  [3 4 2 3 1 4 3 2 4 1]
  [2 2 2 4 2 4 2 3 3 4]
  [1 2 3 1 1 4 4 1 2 2]
  [2 4 2 1 4 4 4 3 1 2]]

 [[2 4 4 4 1 1 4 3 3 1]
  [1 2 4 3 2 1 1 4 2 2]
  [3 2 2 4 2 4 3 3 4 3]
  [3 2 4 1 1 3 3 3 3 4]
  [4 3 4 4 2 4 2 4 1 2]]

 [[3 3 1 4 1 2 2 4 3 3]
  [4 1 2 2 1 2 2 4 4 1]
  [3 4 3 1 2 3 4 4 4 1]
  [1 2 3 4 3 4 2 1 4 3]
  [2 4 1 2 3 4 4 4 2 2]]

 [[4 3 3 3 1 3 4 1 4 2]
  [4 4 4 1 2 4 4 1 1 3]
  [4 3 4 1 3 2 1 3 1 1]
  [3 4 2 4 3 2 3 3 1 4]
  [1 2 3 1 4 1 4 2 4 4]]]


Finally, a property of numpy that is really important is broadcasting. The goal of broadcasting is to simplify the vectorization of certain operations when the vectors do not have the same shape. For example you can easily perform element-wise multiplication.

To test this try doing an element-wise multiplication of the vector x and matrix y below

In [56]:
### To be completed (2-5)
x = np.random.randn(3,1)
y = np.random.randn(3, 5)
result = np.broadcast(x,y)

print("X: ",x)
print("Y: ")
print(y)
print("X shape is: ",x.shape)
print("Y shape is: ",y.shape)
print("Element-wise multiplication shape:", result.shape)
print("Element-wise multiplication result:")
print(result)


X:  [[ 0.31233855]
 [-0.46734826]
 [-0.77296915]]
Y: 
[[ 1.42134218 -0.47125222 -0.35317775  0.36009217 -0.81570789]
 [-0.7265959   0.76184925 -0.85753273 -1.0239198  -0.73582339]
 [ 0.40607114 -0.19709286  1.2786101  -0.93824172 -0.2819199 ]]
X shape is:  (3, 1)
Y shape is:  (3, 5)
Element-wise multiplication shape: (3, 5)
Element-wise multiplication result:


Another very powerful tool in numpy is indexing. You can use either an integer vector or a boolean vector to choose which indexes you want to extract from your numpy tensor.

Consider that we want to extract all elements from the first line of your vector y that have a higher value than 1, you would have to do:

In [57]:
first_row = y[0]
first_row_higher_than_one = first_row > 1
print("Result: ", first_row[first_row_higher_than_one])

Result:  [1.42134218]


You can also choose specific lines to query, for example if you want to query lines 0 and 2

In [58]:
rows = [0,2]
rows_result = y[rows]
values_higher_than_one = rows_result > 1
print("Result: ", rows_result[values_higher_than_one])

Result:  [1.42134218 1.2786101 ]


You can also save and load your numpy tensors using np.savez and np.load. This will be really important as this enable you to generate your data only once instead of having to do all the calculations every time you need your data.

In [59]:
filename = "x.npz"
source_tensor = x
np.savez(filename,data=source_tensor)

In [60]:
loaded_npz = np.load(filename)
loaded_tensor = loaded_npz["data"]
print("Your tensor was loaded and contains: ", loaded_tensor)

Your tensor was loaded and contains:  [[ 0.31233855]
 [-0.46734826]
 [-0.77296915]]


Part 3 - Application to an EEG + ECG dataset
--

Let's load some EEG + ECG data acquired with OpenBCI and visualize it

In [61]:
import matplotlib.pyplot as plt

In [62]:
### The next command is not python, but is specific to jupyter.

%matplotlib inline

from mne.io import read_raw_edf # This is the function to open the raw data

import matplotlib.pyplot as plt # We also import the plotting functions from matplotlib

The following cell opens the data and fixes the data structure - just run it.

Before running this cell, if you are using Google Colab, you should upload the file "eeg_ecg.edf" on your drive, from the github repository : https://github.com/brain-bzh/health_exg/blob/master/TP/data/eeg_ecg.edf

In [64]:
filepath = '/content/eeg_ecg.edf' #### Set path to file here,

Raw = read_raw_edf(filepath,stim_channel=False)
# The second argument is neeeded, otherwise the function assumes that the last channel
# is a "stimulation" channel, but in our case we only have EEG channels

#from mne.channels import read_montage
# We read the electrode position from the standard template positions
#montage = read_montage(kind='standard_1020',ch_names=Raw.ch_names)

scales = dict(eeg='auto') ### This is necessary because the data acquired by openBCI

Raw.load_data()

Extracting EDF parameters from /content/eeg_ecg.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 15499  =      0.000 ...    61.996 secs...


<RawEDF | eeg_ecg.edf, 5 x 15500 (62.0 s), ~614 KiB, data loaded>

Information about the data can be obtained by examining the "info" structure from the Raw object.

Let's print it .

In [65]:
print(Raw.info)

<Info | 8 non-empty values
 bads: []
 ch_names: C4, P4, O2, EOG, ECG
 chs: 5 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2020-06-19 10:49:12 UTC
 nchan: 5
 projs: []
 sfreq: 250.0 Hz
 subject_info: <subject_info | his_id: >
>


Most importantly, we can see the channel names and the sampling frequency.

The data can be fetched into a numpy array, using the "get_data()" method.

In [66]:
exg_array = Raw.get_data()

What is the shape of this array ? What do the respective dimensions correspond to ?
What is the duration of the recording (in seconds) ?

In [68]:
print(exg_array.shape)


(5, 15500)


ECG Analysis
--

The Raw.ch_names gives the names of all electrodes. Which index corresponds to the ECG ?

In [ ]:
ECG correspond à l'index 4

The Raw.times vector gives the time points of measurements, in seconds.

Thus, it can be used to plot the data.

In the cell below:
- create an time_indices vector, containing the indices of the first five seconds of the Raw.times vector
- generate a x vector as using those time indices
- create a y vector that selects the first five seconds of ECG
- use plt.plot(x,y) to plot the first five seconds of data of ECG

In [69]:
time_indices = [0,1,2,3,4]
x = time_indices
y = []

Can you identify the PQRST complex ? How long is approximately a whole cycle ? What about the T-wave ?

Now we would be interested in analysis Heart Rate Variability, by extracting the times corresponding to the peak of the R wave.

Try to perform this using the [find_peaks](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) function from scipy and find the peaks corresponding to the first 5 seconds of ECG

A few things to note :
- find_peaks works for local maxima.
- You have to set a minimal distance between two peaks


In [ ]:
from scipy.signal import find_peaks

### TO BE COMPLETED (3-4)


Once you have found the times of the peak, plot them aligned with the ECG signal. You can use plt.plot, followed by plt.stem, like this (assuming you have named R_times the vector containing the times correspond to the peaks of the R waves)

In [ ]:
plt.plot(x,y)
plt.stem(R_times,200*np.ones_like(R_times),'r')

This seems to work fine on the first five seconds. Now, can you do it on the whole recording ? A longer section of the recording ?

In [ ]:
### TO BE COMPLETED (3-5)

Next step : we are going to estimate heart rate variability.

First, compute the durations between peak R times.

In [ ]:
#### TO BE COMPLETED (3-6)


Visualize all those durations using an histogram, provided by matplotlib plt.hist()

In [ ]:
# To be completed (3-7)

Calculate the average heart rate in Beats Per Minute

In [ ]:
### To be computed (3-8)


Part 4 - EEG Analysis
--

Now we will analyse the first four electrodes of the exg_array, corresponding to EEG electrodes.

What are the names of those electrodes ?

Look up how they are placed by checking the 10/20 EEG electrode placement.

In [ ]:
### To be completed (4-1)


Use what we have learned so far to plot a few segments of EEG data.

What can we notice when looking at the signal globally ?

In [ ]:
### To be completed (4-2)


We will preprocess this data using filtering. This can be done using the method "filter" from MNE.

More background on filtering can be found [here](https://mne.tools/stable/auto_tutorials/discussions/plot_background_filtering.html#disc-filtering)

The filter method modifies the data in place, so we work on a copy.

In [ ]:
raw_filt = Raw.copy()

We will remove two things with filtering : slow trend, and high frequency noise due to line noise (> 40 Hz)

In [ ]:
#TO be completed (4-3)

Plot the result

In [ ]:
# To be completed (4-4)

Estimating the Power Spectral Density of Raw Data
--

We are using [MNE](https://mne.tools/stable/auto_tutorials/index.html) to load and process the EEG data.

The data is managed using an object, Raw, which includes methods for visualization, filtering, and much more.

We can directly plot the Power Spectral density (PSD) using the compute_psd method of the Raw object. A few things :
- Use the "picks" argument to select only the first four electrodes, as the fifth one is the ECG.
- Compare the filtered and raw version


In [ ]:
### TO BE COMPLETED  (4-5)